const CHANGE_ONLINE = 'CHANGE_ONLINE';

const INIT_CLIENTS = 'INIT_CLIENTS';
const ADD_CLIENT = 'ADD_CLIENT';
const REMOVE_CLIENT = 'REMOVE_CLIENT';
const EDIT_CLIENT = 'EDIT_CLIENT';
const UPDATE_CLIENT = 'UPDATE_CLIENT';

const INIT_SHOPS = 'INIT_SHOPS';
const ADD_SHOP = 'ADD_SHOP';
const REMOVE_SHOP = 'REMOVE_SHOP';
const EDIT_SHOP = 'EDIT_SHOP';
const UPDATE_SHOP = 'UPDATE_SHOP';


const INIT_ORDERS = 'INIT_ORDERS';
const ADD_ORDER = 'ADD_ORDER';
const REMOVE_ORDER = 'REMOVE_ORDER';
const UPDATE_ORDER = 'UPDATE_ORDER';

const ADD_NOTI = 'ADD_NOTI';

export {
  CHANGE_ONLINE,
  INIT_CLIENTS,
  ADD_CLIENT,
  REMOVE_CLIENT,
  EDIT_CLIENT,
  UPDATE_CLIENT,
  INIT_SHOPS,
  ADD_SHOP,
  REMOVE_SHOP,
  EDIT_SHOP,
  INIT_ORDERS,
  ADD_ORDER,
  REMOVE_ORDER,
  UPDATE_ORDER,
  UPDATE_SHOP,
  ADD_NOTI,
}
